export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_SUMMONER_SUCCESS = 'LOAD_SUMMONER_SUCCESS';
export const LOAD_CURRENT_GAME_DATA_SUCCESS = 'LOAD_CURRENT_GAME_DATA_SUCCESS';
export const LOAD_CURRENT_GAME_DATA_FAILURE = 'LOAD_CURRENT_GAME_DATA_FAILURE';
export const LOAD_CURRENT_GAME = 'LOAD_CURRENT_GAME';

export const LOAD_STARTED = 'LOAD_STARTED';
export const LOAD_SUCCESS = 'LOAD_SUCCESS';
export const LOAD_FAILURE = 'LOAD_FAILURE';
