export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_SUMMONER_SUCCESS = 'LOAD_SUMMONER_SUCCESS';
export const LOAD_CURRENT_GAME_DATA_SUCCESS = 'LOAD_CURRENT_GAME_DATA_SUCCESS';
export const LOAD_CURRENT_GAME = 'LOAD_CURRENT_GAME';
